spring.application.name=Shoppers-Point
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Ayan1234n@
spring.jpa.hibernate.ddl-auto=update
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=maityayan800@gmail.com
spring.mail.password=jbewcmosapjmtsbp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.transport.protocol=smtp
app.regex.email=^[A-Za-z0-9+_.-]+@(.+)$
address.regex=^(?!\s)([A-Za-z ]*\S)?$
jwt.secret=U2VjcmV0S2V5Rm9ySlNXVG9rZW5HZW5lcmF0aW9uMTIzIQ==
age.cookie=0
reset.password.token.time=15
activation.token.time=3
refresh.expiration=86400
access.expiration=900
server.address=0.0.0.0
server.port=8082
refresh.expiration.time=86400000
access.expiration.time=900000
password.expired.day=30
customerRole=CUSTOMER
sellerRole=SELLER
email.name=ayan.maity@tothenew.com
admin.email.name=admin@gmail.com
image.user=user
image.product.variation=product_variation_primary
image.product.variation.secondary=product_variation_secondary
id.value=100
success.message=SUCCESS
error.count=Error Count : 1
spring.messages.basename=messages/messages
spring.web.resources.static-locations=file:images/

